# Generated by Django 5.0.2 on 2024-02-26 17:00

import django.core.validators
import pdfapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='image',
            field=models.FileField(default=0, upload_to=pdfapp.models.fixed_imagename),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='file',
            field=models.FileField(help_text='upload a pdf file.', upload_to=pdfapp.models.fixed_filename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='only PDF files are allowed. ')]),
        ),
    ]
